# Generated by Django 5.2.10 on 2026-01-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_alter_experiencialaboral_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
