# Generated by Django 5.2.10 on 2026-01-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_alter_experiencialaboral_options_and_more'),
    ]

    operations = [
    ]
